### ISSUE TITLE
A bug in the test code of element detection part

### ISSUE THREAD

**Issue by zhaowei-wang-nlp** [thunlp/CLAIM#1]
In the element branch, /tools/test_tool.py line 37 result = result + results["output"].
The dictionary 'results' doesn't have the key "output"

**Comment by felix-ky** [comment]
> 



> In the element branch, /tools/test_tool.py line 37 result = result + results["output"]. The dictionary 'results' doesn't have the key "output"

How to solve that problem?

**Comment by xcjthu** [comment]
We evaluate the models on the test code by adding "--do_test" option in train.py
