### ISSUE TITLE
Data leakage problem about TF-IDF model on the SCM task

### ISSUE THREAD

**Issue by zhaowei-wang-nlp** [thunlp/CLAIM#2]
I read your TF-IDF code in the SCM branch.  I find that the vectorization process uses the validation data. Obviously, there is a data leakage problem if you use the validation data.

**Comment by xcjthu** [comment]
Thanks a lot for your comments! As the validation dataset and the training dataset follow the same distribution, there are no significant performance differences after we fix the code.
